# Convolutional Neural Network

### Importing the libraries

In [2]:
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

In [3]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Preprocessing the Training set

In [4]:
# We preprocess the images dataset to introduce some variety in images such as zoomed, sheared, flipped etc. to avoid overfitting the model
train_datagen = ImageDataGenerator(
    rescale= 1. / 255,
    shear_range= 0.2,
    zoom_range= 0.2, 
    horizontal_flip= True,
)
# The rescale option normalizes the pixel values i.e how black/white it is (how bright that pixel is). for easier processing in the CNN
training_set = train_datagen.flow_from_directory(
    directory='./dataset/training_set/',
    target_size=(64,64),
    batch_size=32,
    class_mode= 'binary'
)
# Target_size is the size(h,w) of the images before feeding it to the CNN


Found 8000 images belonging to 2 classes.


### Preprocessing the Test set

In [5]:
# we are only rescaling but not applying any transformations
test_datagen = ImageDataGenerator(
    rescale= 1. / 255,
)
test_set = train_datagen.flow_from_directory(
    directory='dataset/test_set',
    target_size=(64,64),
    batch_size=32,
    class_mode= 'binary'
)

Found 2000 images belonging to 2 classes.


## Part 2 - Building the CNN

### Initialising the CNN

In [6]:
cnn = tf.keras.models.Sequential()

### Step 1 - Convolution

In [7]:
cnn.add(tf.keras.layers.Conv2D(filters= 32, input_shape=[64,64,3], kernel_size = 3, activation='relu'))

### Step 2 - Pooling

In [8]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Adding a second convolutional layer

In [9]:
cnn.add(tf.keras.layers.Conv2D(filters= 32, kernel_size = 3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

### Step 3 - Flattening

In [10]:
cnn.add(tf.keras.layers.Flatten())

### Step 4 - Full Connection

In [11]:
cnn.add(tf.keras.layers.Dense(units = 128, activation='relu'))

### Step 5 - Output Layer

In [12]:
# One neuron for the output either cat or dog
cnn.add(tf.keras.layers.Dense(units = 1, activation='sigmoid'))

## Part 3 - Training the CNN

### Compiling the CNN

In [13]:
cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the CNN on the Training set and evaluating it on the Test set

In [14]:
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

Epoch 1/25
250/250 [==============================] - 17s 68ms/step - loss: 0.6782 - accuracy: 0.5744 - val_loss: 0.6605 - val_accuracy: 0.6005
Epoch 2/25
250/250 [==============================] - 16s 66ms/step - loss: 0.6130 - accuracy: 0.6679 - val_loss: 0.5680 - val_accuracy: 0.6960
Epoch 3/25
250/250 [==============================] - 17s 67ms/step - loss: 0.5618 - accuracy: 0.7110 - val_loss: 0.5627 - val_accuracy: 0.7160
Epoch 4/25
250/250 [==============================] - 17s 66ms/step - loss: 0.5236 - accuracy: 0.7374 - val_loss: 0.5177 - val_accuracy: 0.7480
Epoch 5/25
250/250 [==============================] - 17s 67ms/step - loss: 0.4945 - accuracy: 0.7591 - val_loss: 0.5226 - val_accuracy: 0.7415
Epoch 6/25
250/250 [==============================] - 17s 67ms/step - loss: 0.4820 - accuracy: 0.7691 - val_loss: 0.5014 - val_accuracy: 0.7525
Epoch 7/25
250/250 [==============================] - 17s 67ms/step - loss: 0.4583 - accuracy: 0.7812 - val_loss: 0.4913 - val_accuracy:

## Part 4 - Making a single prediction

In [24]:
import numpy as np
from keras.preprocessing import image
# Load image as PIL format
test_image = image.load_img('dataset/single_prediction/cat_or_dog_2.jpg', target_size = (64,64))
# convert PIL format into an array
test_image = image.img_to_array(test_image)
# we trained our cnn in a batch so we cannot directly feed it a single image
# we add another dimension to our array coresponding to a batch
test_image = np.expand_dims(test_image, axis = 0) # new dimension is added at 0th positon of the array
print(test_image)
result = cnn.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
  prediction = 'dog'
else:
  prediction = 'cat'
# first 0 refers to the batch and the second 0 refers to the prediction

[[[[170. 131.  90.]
   [171. 132.  91.]
   [172. 133.  92.]
   ...
   [124.  97.  67.]
   [117.  91.  58.]
   [112.  86.  53.]]

  [[183. 144. 103.]
   [176. 137.  96.]
   [176. 137.  96.]
   ...
   [ 26.  19.   9.]
   [ 31.  25.  13.]
   [ 31.  25.  13.]]

  [[178. 140. 103.]
   [176. 138. 101.]
   [176. 138. 101.]
   ...
   [129.  98.  69.]
   [120.  92.  55.]
   [127.  99.  62.]]

  ...

  [[188. 181. 165.]
   [200. 193. 174.]
   [209. 207. 186.]
   ...
   [ 30.  53.  37.]
   [ 21.  44.  28.]
   [ 29.  52.  36.]]

  [[191. 189. 166.]
   [198. 191. 172.]
   [207. 199. 178.]
   ...
   [ 30.  53.  37.]
   [ 32.  53.  38.]
   [ 28.  49.  34.]]

  [[190. 188. 176.]
   [188. 185. 170.]
   [197. 190. 174.]
   ...
   [ 32.  55.  39.]
   [ 28.  49.  34.]
   [ 37.  58.  43.]]]]
1/1 [==============================] - 0s 8ms/step


In [25]:
print(prediction)

dog
